name = "BayeredImages"
uuid = "f1ec69b2-2eff-4ddc-91c0-bbce45477d89"
version = "0.1.0-dev"
authors = ["Brandon Flores <bsflores@wisc.edu> and contributors"]

[weakdeps]
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"

[extensions]
BayeredImagesFITSIOExt = "FITSIO"

[compat]
FITSIO = "0.17.5"
julia = "1.10"
